spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        default_schema: customer_control
  liquibase:
    enabled: true
    contexts: default
    change-log: classpath:db/changelog/db.changelog-master.yaml
#    default-schema: ${spring.jpa.properties.hibernate.default_schema}
logging:
  level:
    root: info
    "liquibase": info
